spring:
  datasource:
    username: root
    password: qwe123
    url: jdbc:mysql://yoryIP:3307/vote2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource

#   执行数据库文件
#    指定是否初始化
#    initialization-mode: always
#    指定后缀data/schema-xxxx.sql
#    platform: xxxx
#    运行建表语句；
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql

    #   数据源其他配置
#    初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
#    配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，指定每个连接上PSCache的大小
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
